spring:
  datasource:
    url: ec2-54-247-78-30.eu-west-1.compute.amazonaws.com
    username: waatqrpyucphfv
    password: 9322700142eb138220857d26dbd510eaf6c82cace6fd6c4be084197ccfc96447
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
server:
  port: 9999