spring:
  datasource:
    url: ec2-54-247-79-178.eu-west-1.compute.amazonaws.com
    username: dexdzjntmwmfci
    password: 71daa06afa7b51085b5b265ba77bcaeb0e5206276806c1f4395264e6e0315190
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
server:
  port: 9999